"""Initial Migration

Revision ID: dfe683abc497
Revises: bd968945d044
Create Date: 2019-09-30 11:22:59.300213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe683abc497'
down_revision = 'bd968945d044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('blog', 'blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('blog', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blog', 'content')
    # ### end Alembic commands ###
